apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dataplane-clusters
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - git:
        repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/dataplanes.git
        revision: main
        directories:
          - path: "clusters/*"
  template:
    metadata:
      name: "cluster-{{path.basename}}"
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/platform.git
          targetRevision: main
          path: charts/argocd-cluster
          helm:
            releaseName: "cluster-{{path.basename}}"
            valueFiles:
              - $values/{{path.basename}}/values.yaml
        - repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/dataplanes.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
