apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dataplanes
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - git:
        repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/dataplanes.git
        revision: main
        files:
          - path: "dataplanes/*.yaml"
  template:
    metadata:
      name: "dataplane-{{cluster}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      sources:
        - repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/platform.git
          targetRevision: main
          path: charts/dataplane-cluster
          helm:
            releaseName: "dataplane-{{cluster}}"
            valueFiles:
              - $values/dataplanes/{{path.basename}}
        - repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/dataplanes.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
