apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/platform.git
    targetRevision: main
    path: bootstrap/gogs
  destination:
    server: https://kubernetes.default.svc
    namespace: gogs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
