apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: ministack
spec:
  credentials:
    source: Secret
    secretRef:
      name: ministack-aws-credentials
      namespace: crossplane-system
      key: creds
  endpoint:
    hostnameImmutable: true
    services: [s3]
    url:
      type: Static
      static: http://ministack.ministack.svc.cluster.local:4566
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_region_validation: true
  s3_use_path_style: true
