apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/platform.git
      targetRevision: main
      path: gitops/apps
      directory:
        exclude: |
          !*.yaml
          !*.yml
    - repoURL: http://gogs.gogs.svc.cluster.local:3000/gitadmin/platform.git
      targetRevision: main
      path: gitops/appset
      directory:
        exclude: |
          !*.yaml
          !*.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
