apiVersion: lab.example.org/v1alpha1
kind: DataPlane
metadata:
  name: demo-02
  namespace: default
spec:
  compositionRef:
    name: xdataplanes.lab.example.org
  parameters:
    spoke: spoke-02
    image: nginxdemos/hello
    replicas: 2
