apiVersion: lab.example.org/v1alpha1
kind: DataPlane
metadata:
  name: demo-01
  namespace: default
spec:
  compositionRef:
    name: xdataplanes.lab.example.org
  parameters:
    spoke: spoke-01
    image: nginxdemos/hello
    replicas: 1
